### PR TITLE
Try out conda-forge automerging.

### PR DESCRIPTION
**Pull request by ian-r-rose**
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by necaris — APPROVED** [review]

**Comment by jrbourbeau** [comment]
This is a neat feature. Just wanted to point out that PRs from the conda-forge bot won't include dependency updates. In those cases, we'll want to avoid automerging

**Comment by necaris** [comment]
Will that affect us if we're using requirements. txt instead of meta.yaml ?

On August 13, 2021 4:18:10 PM UTC, James Bourbeau ***@***.***> wrote:
>This is a neat feature. Just wanted to point out that PRs from the conda-forge bot won't include dependency updates. In those cases, we'll want to avoid automerging 
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/conda-forge/coiled-feedstock/pull/43#issuecomment-898574929
-- 
"A mind all logic is like a knife all blade -- it makes the hand bleed which uses it." -- Rabindranath Tagore

**Comment by jrbourbeau** [comment]
I don't quite follow, the conda-forge package should always use `meta.yaml`. What I mean is when the conda-forge bot opens up PRs, it won't update these package dependencies

https://github.com/conda-forge/coiled-feedstock/blob/5eb0e41900d45f19a4eda96daa602aba4a5b9bd5/recipe/meta.yaml#L25-L36

That has to be done manually

**Comment by ian-r-rose** [comment]
> This is a neat feature. Just wanted to point out that PRs from the conda-forge bot won't include dependency updates. In those cases, we'll want to avoid automerging

Good point. At least in some cases that will result in a CI failure so the merge will not go through, but not all

**Comment by jrbourbeau** [comment]
Instead of always automerging, we might consider expanding merge access to other relevant folks

**Pull request merged**
