### PR TITLE
Add `coiled` entrypoint

### PR DESCRIPTION
**Pull request by jrbourbeau**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @FabioRosado @ncclementi

### CODE REVIEW

**Comment by dchudz** [comment]
Seems okay to me? I'm not an expert.

**Comment by jrbourbeau** [comment]
For context, @FabioRosado found that the `coiled` CLI (e.g. `coiled --version`) works totally fine on Windows when installed from PyPI with `pip`, but found that he would get a

```
'coiled' is not recognized as an internal or external command,
operable program or batch file.
```

error when using coiled installed from `conda-forge`. After looking at the `coiled-feedstock` meta, I noticed we're missing an `entry_points` entry in our `build` section which the [conda-forge docs](https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=entry_points#noarch-python) say is needed for `noarch` packages that use `console_scripts` in their `setup.py` (which `coiled` does).

**Comment by FabioRosado** [comment]
So this is the missing thing, nice find!

**Review by dchudz — APPROVED** [review]

**Comment by dchudz** [comment]
Sounds good. You want me to merge this?

**Review by ian-r-rose — APPROVED** [review]
LGTM, thanks!

**Comment by jrbourbeau** [comment]
Yeah, I think there's a good chance this fixes the Windows issue we were running into with @FabioRosado. This is also very easy to revert if needed

**Pull request merged**
